// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GRpc.Messages {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgdNZXNzYWdlGg1tZXNzYWdlLnByb3RvMs0BChBD",
            "YW5kaWRhdGVTZXJ2aWNlEjsKCENyZWF0ZUN2EhIuTWVzc2FnZS5DYW5kaWRh",
            "dGUaGS5NZXNzYWdlLkNyZWF0ZUN2UmVzcG9uc2UoARI7CgpEb3dubG9hZEN2",
            "EhcuTWVzc2FnZS5Eb3dubG9hZEJ5TmFtZRoSLk1lc3NhZ2UuQ2FuZGlkYXRl",
            "MAESPwoQQ3JlYXRlRG93bmxvYWRDdhISLk1lc3NhZ2UuQ2FuZGlkYXRlGhMu",
            "TWVzc2FnZS5DYW5kaWRhdGVzKAEwAUIQqgINR1JwYy5NZXNzYWdlc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GRpc.Messages.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
