// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GRpc.Messages {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgdNZXNzYWdlGg1tZXNzYWdlLnByb3RvMsQBChBD",
            "YW5kaWRhdGVTZXJ2aWNlEjkKCENyZWF0ZUN2EhIuTWVzc2FnZS5DYW5kaWRh",
            "dGUaGS5NZXNzYWdlLkNyZWF0ZUN2UmVzcG9uc2USOQoKRG93bmxvYWRDdhIX",
            "Lk1lc3NhZ2UuRG93bmxvYWRCeU5hbWUaEi5NZXNzYWdlLkNhbmRpZGF0ZRI6",
            "ChBDcmVhdGVEb3dubG9hZEN2EhIuTWVzc2FnZS5DYW5kaWRhdGUaEi5NZXNz",
            "YWdlLkNhbmRpZGF0ZUIQqgINR1JwYy5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GRpc.Messages.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
